import React, { useState } from "react";
import {
  Box,
  Typography,
  TextField,
  Button,
  ButtonGroup,
  Chip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  CircularProgress
} from "@mui/material";
import SparklesIcon from "@mui/icons-material/AutoAwesome";
import PlayIcon from "@mui/icons-material/PlayArrow";
import VerifyIcon from "@mui/icons-material/VerifiedUser";
import SaveIcon from "@mui/icons-material/Save";
import ErrorIcon from "@mui/icons-material/ErrorOutlined";
import CheckIcon from "@mui/icons-material/CheckCircleOutlined";
import { useAppStore } from "../store/useAppStore";

export const PromptPanel: React.FC = () => {
  const {
    prompt,
    setPrompt,
    generatedSql,
    setGeneratedSql,
    loadingStates,
    errors,
    selectedSchemaId,
    generateSql,
    validateSql,
    executeSql,
    saveQuery,
    clearSqlErrors
  } = useAppStore();

  const [validationSuccess, setValidationSuccess] = useState<string | null>(null);
  
  // Save Query Dialog State
  const [saveOpen, setSaveOpen] = useState(false);
  const [saveName, setSaveName] = useState("");
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState("");

  const examples = [
    "Show total revenue generated by each customer during the last 30 days.",
    "List all products in stock with their categories.",
    "Count the number of orders handled by each employee.",
    "Find the top 3 highest spending customers in USA."
  ];

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setValidationSuccess(null);
    try {
      await generateSql(prompt);
    } catch (e) {
      console.error(e);
    }
  };

  const handleValidate = async () => {
    if (!generatedSql.trim()) return;
    setValidationSuccess(null);
    const isValid = await validateSql(generatedSql);
    if (isValid) {
      setValidationSuccess("SQL query parsed successfully and matches SELECT constraints.");
    }
  };

  const handleExecute = async () => {
    if (!generatedSql.trim()) return;
    setValidationSuccess(null);
    await executeSql(generatedSql);
  };

  const handleSaveOpen = () => {
    setSaveName("");
    setSaveError("");
    setSaveOpen(true);
  };

  const handleSaveSubmit = async () => {
    if (!saveName.trim()) {
      setSaveError("Please provide a name for this saved query.");
      return;
    }
    setSaving(true);
    setSaveError("");
    try {
      await saveQuery(saveName);
      setSaveOpen(false);
    } catch (err: any) {
      setSaveError(err.message || "Failed to save the query.");
    } finally {
      setSaving(false);
    }
  };

  return (
    <Box sx={{ display: "flex", flexDirection: "column", gap: 2 }}>
      {/* Title & Desc */}
      <Box>
        <Typography variant="h6" sx={{ fontWeight: 700, mb: 0.5 }}>
          AI Query Interface
        </Typography>
        <Typography variant="body2" color="text.secondary">
          Translate natural language questions into safe SQL SELECT statements, review them, and run executions.
        </Typography>
      </Box>

      {/* Input Field */}
      <TextField
        placeholder="Enter your natural language question here..."
        multiline
        rows={3}
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        fullWidth
        disabled={!selectedSchemaId || loadingStates.generating}
      />

      {/* Example Chips */}
      <Box sx={{ display: "flex", flexWrap: "wrap", gap: 1, alignItems: "center" }}>
        <Typography variant="caption" color="text.secondary" sx={{ mr: 1, fontWeight: 600 }}>
          Quick Examples:
        </Typography>
        {examples.map((ex, idx) => (
          <Chip
            key={idx}
            label={ex.substring(0, 45) + (ex.length > 45 ? "..." : "")}
            size="small"
            onClick={() => setPrompt(ex)}
            disabled={!selectedSchemaId}
            sx={{
              backgroundColor: "rgba(255, 255, 255, 0.03)",
              border: "1px solid rgba(255, 255, 255, 0.05)",
              cursor: "pointer",
              "&:hover": {
                backgroundColor: "rgba(255, 255, 255, 0.08)"
              }
            }}
          />
        ))}
      </Box>

      {/* Action Buttons */}
      <Box sx={{ display: "flex", flexWrap: "wrap", justifyContent: "space-between", alignItems: "center", gap: 2, mt: 1 }}>
        <Button
          variant="contained"
          disabled={!prompt.trim() || !selectedSchemaId || loadingStates.generating}
          onClick={handleGenerate}
          startIcon={loadingStates.generating ? <CircularProgress size={16} color="inherit" /> : <SparklesIcon />}
          sx={{ py: 1, px: 2 }}
        >
          {loadingStates.generating ? "Generating SQL..." : "Generate SQL"}
        </Button>

        <ButtonGroup variant="outlined" size="medium" disabled={!generatedSql.trim() || !selectedSchemaId}>
          <Button
            onClick={handleValidate}
            startIcon={loadingStates.validating ? <CircularProgress size={14} color="inherit" /> : <VerifyIcon />}
          >
            Validate
          </Button>
          <Button
            onClick={handleExecute}
            variant="contained"
            color="success"
            startIcon={loadingStates.executing ? <CircularProgress size={14} color="inherit" /> : <PlayIcon />}
            sx={{
              backgroundColor: "var(--success)",
              "&:hover": { backgroundColor: "#0e9f6e" }
            }}
          >
            Execute Query
          </Button>
          <Button onClick={handleSaveOpen} startIcon={<SaveIcon />}>
            Save Query
          </Button>
        </ButtonGroup>
      </Box>

      {/* Errors & Banners Display */}
      {errors.sql.length > 0 && (
        <Box
          className="fade-in"
          sx={{
            p: 1.5,
            borderRadius: 1,
            bgcolor: "rgba(239, 68, 68, 0.1)",
            border: "1px solid rgba(239, 68, 68, 0.25)",
            color: "var(--error)",
            display: "flex",
            alignItems: "flex-start",
            gap: 1.5
          }}
        >
          <ErrorIcon sx={{ fontSize: 20, mt: 0.25, flexShrink: 0 }} />
          <Box>
            <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
              Query Validation Failure
            </Typography>
            {errors.sql.map((err, i) => (
              <Typography key={i} variant="caption" display="block">
                • {err}
              </Typography>
            ))}
          </Box>
        </Box>
      )}

      {validationSuccess && (
        <Box
          className="fade-in"
          sx={{
            p: 1.5,
            borderRadius: 1,
            bgcolor: "rgba(16, 185, 129, 0.1)",
            border: "1px solid rgba(16, 185, 129, 0.25)",
            color: "var(--success)",
            display: "flex",
            alignItems: "center",
            gap: 1.5
          }}
        >
          <CheckIcon sx={{ fontSize: 20, flexShrink: 0 }} />
          <Typography variant="caption" sx={{ fontWeight: 600 }}>
            {validationSuccess}
          </Typography>
        </Box>
      )}

      {/* Save Query Name Dialog Modal */}
      <Dialog open={saveOpen} onClose={() => !saving && setSaveOpen(false)}>
        <DialogTitle sx={{ display: "flex", alignItems: "center", gap: 1 }}>
          <SaveIcon color="primary" /> Save Generated SQL
        </DialogTitle>
        <DialogContent dividers sx={{ minWidth: 320 }}>
          {saveError && (
            <Box
              sx={{
                p: 1.5,
                mb: 2,
                borderRadius: 1,
                bgcolor: "rgba(239, 68, 68, 0.15)",
                border: "1px solid rgba(239, 68, 68, 0.3)",
                color: "var(--error)"
              }}
            >
              <Typography variant="caption" sx={{ fontWeight: 500 }}>
                {saveError}
              </Typography>
            </Box>
          )}

          <TextField
            label="Query Name"
            placeholder="e.g. High Spending Users, 30 Day Revenue"
            fullWidth
            size="small"
            value={saveName}
            onChange={(e) => setSaveName(e.target.value)}
            disabled={saving}
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setSaveOpen(false)} disabled={saving} color="inherit">
            Cancel
          </Button>
          <Button onClick={handleSaveSubmit} variant="contained" disabled={saving}>
            {saving ? "Saving..." : "Save Query"}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};
export default PromptPanel;
